---
- name: Disable selinux
  selinux: state=disabled
  when: selinux_enabled == true

- name: Disable sshd strict modes
  lineinfile:
      backrefs: yes
      dest: /etc/ssh/sshd_config
      regexp: "^#StrictModes yes"
      line: "StrictModes no"
  notify: restart sshd

- name: Install Pulp dnf repository
  when: ansible_distribution == 'Fedora' and ansible_distribution_version|int < 24
  get_url:
      url: https://repos.fedorapeople.org/repos/pulp/pulp/fedora-pulp.repo
      dest: /etc/yum.repos.d/fedora-pulp.repo

- name: Install dnf config-manager
  dnf: name=dnf-command(config-manager) state=present

- name: Enable Pulp Nightly repository
  command: dnf config-manager --set-enabled pulp-nightlies
  when: ansible_distribution == 'Fedora' and ansible_distribution_version|int < 24 and pulp_nightly_repo_enabled == false

# These can go away when https://fedorahosted.org/spin-kickstarts/ticket/59 is fixed
- stat:
      path: /etc/sudoers.d/vagrant-nopasswd
  name: Detect vagrant sudoers file
  register: vagrant_nopasswd
- lineinfile:
      dest: "{{ vagrant_nopasswd.stat.path }}"
      regexp: '^vagrant'
      line: 'vagrant ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
      mode: 0440
  when: vagrant_nopasswd.stat.exists
  name: Rejigger vagrant sudoers file

- name: Install packages
  dnf: name={{ item }} state=present
  with_items:
      - git
      - dstat
      - fpaste
      - graphviz
      - gcc
      - iotop
      - jnettop
      - koji
      - httpie
      - mock
      - plantuml
      - python-django-bash-completion
      - python-gofer-qpid
      - python-ipdb
      - python-qpid
      - python-qpid-qmf
      - python-setuptools
      - python-sphinx
      - python-virtualenvwrapper
      - python2-rpdb
      - redhat-lsb-core
      - rpm-build
      - ruby-devel
      - telnet
      - tito
      - yum-utils
      - zlib-devel

- name: allow vagrant user to read the systemd journal
  user:
      name: vagrant
      state: present
      groups: systemd-journal
      append: true

- name: allow vagrant user to use mock
  user:
      name: vagrant
      state: present
      groups: mock
      append: true

- name: Install Pulp RPM dependencies
  dnf: name={{ item }} state=present
  with_items: "{{ pulp_rpm_dependencies }}"

- name: Ensure homedir mode suitable for ssh keys
  file: dest=/home/{{ ansible_env.SUDO_USER }} mode=0750

- copy: src=bashrc dest=/home/{{ ansible_env.SUDO_USER }}/.bashrc
- copy: src=drop_database.js dest=/home/{{ ansible_env.SUDO_USER }}/drop_database.js
- copy: src=motd dest=/etc/motd

- include: debug.yml
  # set this to true in extra vars to enable debug-related tasks
  when: pulp_dev_debug
