---
- name: Install packages
  dnf: name={{ item }} state=present
  with_items:
      - mongodb
      - mongodb-server

- name: Disable MongoDB journal
  lineinfile:
      backrefs: yes
      dest: /etc/mongod.conf
      regexp: "^#nojournal = true"
      line: "nojournal = true"
  notify: restart mongod

- name: Start and enable services
  service: name=mongod state=started enabled=yes
