---
- name: Install basic packages
  dnf: name={{ item }} state=present
  with_items:
      - bash-completion
      - fedora-easy-karma
      - htop
      - screen
      - tmux
      - tree
      - vim-enhanced

- name: Install packages requires to gather Pulp facts
  dnf: name={{ item }} state=present
  with_items:
      - rpm-build

- name: Gathering Pulp facts
  pulp_facts:
