repositories:
  - name: pulp
    git_url: https://github.com/pulp/pulp.git
    git_branch: 2.21-release
    version: 2.21.3-1
  - name: pulp_puppet
    git_url: https://github.com/pulp/pulp_puppet.git
    git_branch: 2.21-release
  - name: pulp_rpm
    git_url: https://github.com/pulp/pulp_rpm.git
    git_branch: 2.21-release
  - name: pulp_docker
    git_url: https://github.com/pulp/pulp_docker.git
    git_branch: 3.2-release
  - name: pulp_ostree
    git_url: https://github.com/pulp/pulp_ostree.git
    git_branch: 1.3-release
  - name: pulp_python
    git_url: https://github.com/pulp/pulp_python.git
    git_branch: 2.0-release
  - name: crane
    git_url: https://github.com/pulp/crane.git
    git_branch: 3.3-release
